### ISSUE TITLE
Refatorar esquema do banco de dados para o modelo de negócio

### ISSUE THREAD

**Issue by willy-r** [otaldonuness/meupetminhavida-back#14]
# Descrição:

Após reunião do back-end no dia 20/06, decidimos reformular algumas coisas em relação ao banco de dados para que o mesmo fizesse mais sentido no modelo de negócios da aplicação, e aproveitando que não tinha muita coisa ainda implementada, fica fácil a refatoração do mesmo.

Ou seja, a intenção é seguir este novo modelo do banco:
![image](https://github.com/otaldonuness/meupetminhavida-back/assets/47596121/4544cf45-ea7e-40f5-8955-ac511aa768e6)

## Tarefas:

- Refazer models do Prisma baseando-se no banco acima
- Gerar novas migrações com as novas tabelas
- Refatorar onde for necessário, por agora, baseando-se no novo modelo de dados. (vide módulo de `users`)
- Refatorar testes já criados para o novo modelo de dados

## Critérios de aceitação:

- As novas models tenham sido refatoradas
- As novas migrações criadas
- Rotas anteriores funcionando perfeitamente
- Testes passando

**Comment by mahzze** [comment]
On it
